version: 1
builder:
  configs:
    - documentation_targets:
        - EventarcServer
        - FirebaseAuthServer
        - FirebaseStorageSchema
        - FirebaseStorageServer
        - FirestoreSchema
        - FirestoreServer
